### ISSUE TITLE
关于跨境电商交易平台的一些问题想请教一下

### ISSUE THREAD

**Issue by CJ13067257052** [SoftwareCupC/change#11]
关于跨境电商交易平台的一些问题想请教一下，作者可以留一个联系方式吗非常感谢

**Comment by yuzh233** [comment]
你好！yuzh233@gmail.com

**Comment by CJ13067257052** [comment]
是这样的，最近参加一个比赛发现和你这个平台类似，但是主办方提供的需求非常不明确，导致我现在需求有点偏题，因为第一次做这种项目，是个萌新，想请教一下
