### ISSUE TITLE
找不到数据库文件

### ISSUE THREAD

**Issue by kbq670554802** [SoftwareCupC/change#12]
找不到数据库文件，方便给一份吗？谢谢

**Comment by yuzh233** [comment]
这是我们在学校时做的练手项目，好久没维护了，没有参考价值。-------- 原始邮件 --------主题：[SoftwareCupC/change] 找不到数据库文件 (#12)发件人：柯葆青 收件人：SoftwareCupC/change 抄送：Subscribed 找不到数据库文件，方便给一份吗？谢谢
